// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgId.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using scg = global::System.Collections.Generic;
namespace UGameRemove {

  #region Enums
  public enum MsgID {
    None = 0,
    C2SDemo = 1,
    S2CDemo = 2,
  }

  #endregion

}

#endregion Designer generated code
